#!/usr/bin/env python3
"""Generate the MyOS application manifest.

Every `@app` struct under system/MyOS/src/apps becomes one line in
build/apps_manifest.mln, which boot (system/MyOS/src/boot/main.mln) imports
and calls once so the framework (system/MyOS/src/app/app.mln) learns about
each app. An app never registers itself, and the framework never imports an
app: this generated file is the only place that knows both.

MyLang compiles the import graph from main.mln, so an app that is not
imported from somewhere would not be linked at all; the manifest is that
somewhere. Apps are listed alphabetically by struct name, which is also the
launcher menu order.

Usage: gen_app_manifest.py [--out build/apps_manifest.mln] [--quiet]
"""

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from tools.project_paths import MYOS_DIR, REPO_ROOT  # noqa: E402

APPS_DIR = MYOS_DIR / "src" / "apps"
FRAMEWORK = MYOS_DIR / "src" / "app" / "app.mln"

# `@app` (with or without arguments) followed, possibly across lines, by the
# struct it decorates. Comments are stripped first so a commented-out app is
# not picked up.
APP_RE = re.compile(r"@app(?:\s*\([^)]*\))?\s*(?:export\s+)?struct\s+([A-Za-z_][A-Za-z0-9_]*)")
PACKAGE_RE = re.compile(r"^\s*package\s+([A-Za-z_][A-Za-z0-9_]*)\s*;", re.MULTILINE)
COMMENT_RE = re.compile(r"//[^\n]*|/\*.*?\*/", re.DOTALL)


def find_apps():
    found = []
    for source in sorted(APPS_DIR.glob("*.mln")):
        text = COMMENT_RE.sub("", source.read_text(encoding="utf-8"))
        structs = APP_RE.findall(text)
        if not structs:
            continue
        package = PACKAGE_RE.search(text)
        if not package:
            sys.exit(f"{source}: an @app file must declare a package")
        for struct in structs:
            found.append((struct, package.group(1), source))
    found.sort(key=lambda entry: entry[0].lower())
    return found


def render(apps, out_path):
    out_dir = out_path.parent

    def rel(path):
        import os
        return Path(os.path.relpath(path, out_dir)).as_posix()

    lines = [
        "// Generated by qa/runners/gen_app_manifest.py -- do not edit.",
        "// One entry per @app struct under system/MyOS/src/apps, in menu order.",
        "package apps_manifest;",
        "",
        f'import app from "{rel(FRAMEWORK)}";',
    ]
    seen = set()
    for _, package, source in apps:
        if package in seen:
            continue
        seen.add(package)
        lines.append(f'import {package} from "{rel(source)}";')
    lines += ["", "export void register_all() {"]
    for struct, package, _ in apps:
        lines.append(f"    app.add({package}.__app_{struct}_desc());")
    lines += ["}", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--out", type=Path, default=REPO_ROOT / "build" / "apps_manifest.mln")
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args()

    apps = find_apps()
    text = render(apps, args.out)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    if not args.out.exists() or args.out.read_text(encoding="utf-8") != text:
        args.out.write_text(text, encoding="utf-8")
    if not args.quiet:
        names = ", ".join(struct for struct, _, _ in apps) or "(none)"
        print(f"apps manifest: {args.out} [{names}]")


if __name__ == "__main__":
    main()
