#!/usr/bin/env python3
"""Rasterize a TrueType/OpenType font into a MyLang module (MYOS-014).

The output module holds, for each *face* (a weight at a pixel size), the line
metrics plus one anti-aliased glyph per printable ASCII character
(0x20..0x7E). Glyphs are stored as 8-bit coverage (A8) over their tight
bounding box, which is exactly what the emulator's DMA2D_CMD_MASK_A8 consumes,
so drawing a glyph is one accelerator command.

Usage:
    python3 tools/gen_font.py                      # defaults below
    python3 tools/gen_font.py --font path.ttf --out system/MyOS/src/ui/font_sans.mln

Faces are listed in FACES as (name, weight, px). Regular/bold at 1x and 2x UI
scale cover a 1024x768 logical desktop shown on 1024x768 or 2048x1536.
Requires Pillow.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

FIRST = 0x20
LAST = 0x7E
COUNT = LAST - FIRST + 1

# (face name, weight axis value or None for static fonts, pixel size)
FACES = [
    ("regular_1x", 400, 14),
    ("regular_2x", 400, 28),
    ("bold_1x", 600, 16),
    ("bold_2x", 600, 32),
]

CANDIDATE_FONTS = [
    "/usr/share/fonts/google-noto-vf/NotoSans[wght].ttf",
    "/usr/share/fonts/truetype/noto/NotoSans-Regular.ttf",
    "/usr/share/fonts/liberation-sans-fonts/LiberationSans-Regular.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
]


def find_font() -> str:
    for candidate in CANDIDATE_FONTS:
        if Path(candidate).exists():
            return candidate
    sys.exit("no candidate font found; pass --font <path.ttf>")


def load_face(path: str, weight: int | None, px: int) -> ImageFont.FreeTypeFont:
    font = ImageFont.truetype(path, px)
    if weight is not None:
        try:
            axes = font.get_variation_axes()
        except OSError:
            axes = []
        if axes:
            lo, hi = axes[0]["minimum"], axes[0]["maximum"]
            font.set_variation_by_axes([max(lo, min(hi, weight))])
    return font


def rasterize(font: ImageFont.FreeTypeFont, ch: str):
    """Return (advance, bx, by, w, h, bytes) for one glyph.

    bx/by are the offsets of the tight box from the pen position on the line
    top (PIL's default 'la' anchor: left edge, ascender line). bx can be
    negative for glyphs that overhang to the left."""
    advance = int(round(font.getlength(ch)))
    left, top, right, bottom = font.getbbox(ch)
    w, h = right - left, bottom - top
    if w <= 0 or h <= 0:
        return advance, 0, 0, 0, 0, b""
    # Draw at an offset large enough that a negative left bearing still lands
    # inside the image, then crop the box back out.
    pad = 4
    img = Image.new("L", (right + pad * 2, bottom + pad * 2), 0)
    ImageDraw.Draw(img).text((pad, pad), ch, font=font, fill=255)
    box = img.crop((left + pad, top + pad, right + pad, bottom + pad))
    return advance, left, top, w, h, box.tobytes()


def emit(path_out: Path, font_path: str) -> None:
    line_h, ascent, px_list, bold_list = [], [], [], []
    adv, bx, by, gw, gh, off = [], [], [], [], [], []
    data = bytearray()

    for name, weight, px in FACES:
        font = load_face(font_path, weight, px)
        asc, desc = font.getmetrics()
        line_h.append(asc + desc)
        ascent.append(asc)
        px_list.append(px)
        bold_list.append(1 if (weight or 400) >= 500 else 0)
        for code in range(FIRST, LAST + 1):
            a, x, y, w, h, raw = rasterize(font, chr(code))
            adv.append(a)
            bx.append(x)
            by.append(y)
            gw.append(w)
            gh.append(h)
            off.append(len(data))
            data += raw

    def int_array(name: str, values: list[int]) -> str:
        body = ", ".join(str(v) for v in values)
        return f"i32 {name}[{len(values)}] = {{{body}}};\n"

    def byte_array(name: str, values: bytes) -> str:
        lines = []
        for i in range(0, len(values), 24):
            chunk = values[i : i + 24]
            lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk))
        body = ",\n".join(lines) if lines else "    0x00"
        n = max(len(values), 1)
        return f"char {name}[{n}] = {{\n{body}\n}};\n"

    face_names = ", ".join(f"{i}={n}" for i, (n, _, _) in enumerate(FACES))
    out = []
    out.append("package font_sans;\n\n")
    out.append("// GENERATED by tools/gen_font.py -- do not edit by hand.\n")
    out.append(f"// Source font: {Path(font_path).name}\n")
    out.append(f"// Faces: {face_names}\n")
    out.append("//\n")
    out.append("// Anti-aliased proportional font for the desktop UI. Each glyph is an 8-bit\n")
    out.append("// coverage (A8) bitmap over its tight bounding box; graphics.mln hands the\n")
    out.append("// box to DMA2D_CMD_MASK_A8 so drawing a character is one accelerator\n")
    out.append("// command. Metrics are in pixels at the face's own size (no UI scaling here:\n")
    out.append("// the 2x faces exist so a 2048x1536 display gets real 2x glyphs instead of\n")
    out.append("// blown-up 1x ones).\n\n")
    out.append(f"i32 FACE_COUNT = {len(FACES)};\n")
    out.append(f"i32 GLYPH_COUNT = {COUNT};\n\n")
    out.append(int_array("face_line_h", line_h))
    out.append(int_array("face_ascent", ascent))
    out.append(int_array("face_px", px_list))
    out.append(int_array("face_bold", bold_list))
    out.append("\n// Per glyph, indexed face * GLYPH_COUNT + (ch - 0x20).\n")
    out.append(int_array("g_adv", adv))
    out.append(int_array("g_bx", bx))
    out.append(int_array("g_by", by))
    out.append(int_array("g_w", gw))
    out.append(int_array("g_h", gh))
    out.append(int_array("g_off", off))
    out.append("\n")
    out.append(byte_array("g_data", bytes(data)))
    out.append(
        """
export i32 face_count() { return FACE_COUNT; }

// Pick a face: bold != 0 selects the bold weight, scale >= 2 the 2x size.
export i32 face_for(i32 bold, i32 scale) {
    i32 f = 0;
    if (scale >= 2) { f = 1; }
    if (bold != 0) { f = f + 2; }
    return f;
}

export i32 line_height(i32 face) { return face_line_h[face]; }
export i32 ascent(i32 face) { return face_ascent[face]; }
export i32 pixel_size(i32 face) { return face_px[face]; }

// Characters outside 0x20..0x7E draw as '?'.
i32 glyph_index(i32 face, i32 ch) {
    if (ch < 0x20) { ch = '?'; }
    if (ch > 0x7E) { ch = '?'; }
    return face * GLYPH_COUNT + (ch - 0x20);
}

export i32 advance(i32 face, i32 ch) { return g_adv[glyph_index(face, ch)]; }
export i32 bearing_x(i32 face, i32 ch) { return g_bx[glyph_index(face, ch)]; }
export i32 bearing_y(i32 face, i32 ch) { return g_by[glyph_index(face, ch)]; }
export i32 width(i32 face, i32 ch) { return g_w[glyph_index(face, ch)]; }
export i32 height(i32 face, i32 ch) { return g_h[glyph_index(face, ch)]; }

// Address of the glyph's coverage bytes (row-major, stride == width).
export i32 data(i32 face, i32 ch) {
    return (i32)(&g_data[0]) + g_off[glyph_index(face, ch)];
}
"""
    )
    path_out.write_text("".join(out), encoding="utf-8")
    print(f"wrote {path_out} ({len(data)} coverage bytes, {len(FACES)} faces)")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--font", default=None, help="TTF/OTF to rasterize (default: first of CANDIDATE_FONTS)")
    parser.add_argument(
        "--out",
        default=str(Path(__file__).resolve().parents[1] / "system/MyOS/src/ui/font_sans.mln"),
    )
    args = parser.parse_args()
    emit(Path(args.out), args.font or find_font())


if __name__ == "__main__":
    main()
